### ISSUE TITLE
Use stable libhandy

### ISSUE THREAD

**Issue by alice-mkh** [flathub/org.gnome.Glade#10]
Currently it's using the master branch, which is libhandy 1.0 and _does not have stable API yet_! Please use `libhandy-0-0` branch, specifically `v0.0.13` tag (commit `7a193d7692c9c76a1a94f17c4d30b585f77d177c`).

**Comment by albfan** [comment]
Done

**Comment by alice-mkh** [comment]
Where? I don't see any changes so far...
