### ISSUE TITLE
Libhandy 1.0 is out

### ISSUE THREAD

**Issue by sophie-h** [flathub/org.gnome.Glade#12]
https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/609

**Comment by albfan** [comment]
This needs a tag 1.0.0 https://gitlab.gnome.org/GNOME/libhandy/-/tags and in my opinion, libhandy should be a flatpak extension

**Comment by sophie-h** [comment]
The commit is now tagged 1.0.0. Extension sounds reasonable, but maybe libhandy can be kept up to date here until another solution is in place?

**Comment by sophie-h** [comment]
Should be fixed via #13
