### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Glade#25]
If possible, please consider verifying this Flatpak.

Here is more info about verified apps: https://flathub.org/about

**Comment by albfan** [comment]
Done! Thanks for pointing out

**Comment by albfan** [comment]
@xjuan should do it

**Comment by xjuan** [comment]
Done, I assume it takes some time for the website to update

**Comment by albfan** [comment]
I see the blue tick!
